"""remove test column

Revision ID: 9e040432fac9
Revises: 4996d1ec116f
Create Date: 2024-12-23 15:06:30.166906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e040432fac9'
down_revision = '4996d1ec116f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('test_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_column', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
